cloud:
    aws:
        credentials:
            access-key: HHHHHHHHHHHHHHHHHHHHH
            secret-key: AAAAAAAAAAAAAAAAAAAA
        region:
            static: us-east-1
        stack:
            auto: false
        endpoint:
            url: http://localhost/4566

application:
    bucket:
        name: haiitems

server:
    port: 8083