cloud:
    aws:
        credentials:
            access-key: AKIAW3TDPMFXB5HVC76J
            secret-key: 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
        region:
            static: ap-south-1
        stack:
            auto: false
        endpoint:
            local-url: http://localhost/4566
            url: s3.ap-south-1.amazonaws.com

application:
    bucket:
        name: haiitems

server:
    port: 8083